# Generated by Django 5.0 on 2024-12-09 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kullanici',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_soyad', models.CharField(max_length=255)),
                ('baslangic_tarihi', models.DateField()),
                ('uyelik_suresi_ay', models.IntegerField()),
                ('ucret', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tel_no', models.CharField(blank=True, max_length=15, null=True)),
                ('notlar', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='IslemGecmisi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('islem_tipi', models.CharField(max_length=255)),
                ('tarih', models.DateField()),
                ('ucret', models.DecimalField(decimal_places=2, max_digits=10)),
                ('kullanici', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='islem_gecmisi', to='API.kullanici')),
            ],
        ),
        migrations.CreateModel(
            name='UyelikGecmisi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_soyad', models.CharField(max_length=255)),
                ('baslangic_tarihi', models.DateField()),
                ('uyelik_suresi_ay', models.IntegerField()),
                ('ucret', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tel_no', models.CharField(blank=True, max_length=15, null=True)),
                ('kullanici', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uyelik_gecmisi', to='API.kullanici')),
            ],
        ),
    ]
