# Generated by Django 5.0 on 2024-12-10 21:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_alter_kullanici_baslangic_tarihi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kullanici',
            name='baslangic_tarihi',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
