# Generated by Django 5.0 on 2024-12-11 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_alter_kullanici_baslangic_tarihi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='islemgecmisi',
            name='tarih',
            field=models.DateField(auto_now_add=True),
        ),
    ]
