# Generated by Django 5.0 on 2024-12-13 12:32

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0004_alter_islemgecmisi_tarih'),
    ]

    operations = [
        migrations.CreateModel(
            name='MesajGecmisi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mesaj_tarihi', models.DateField(default=django.utils.timezone.now)),
                ('mesaj', models.TextField()),
                ('kullanici', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.kullanici')),
            ],
        ),
    ]
