# Generated by Django 5.0 on 2024-12-13 13:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0005_mesajgecmisi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mesajgecmisi',
            name='mesaj_tarihi',
            field=models.DateField(verbose_name=datetime.date.today),
        ),
    ]
