# Generated by Django 5.0 on 2024-12-19 02:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0007_kullanici_bitis_tarihi'),
    ]

    operations = [
        migrations.AddField(
            model_name='uyelikgecmisi',
            name='bitis_tarihi',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
